version: '3.4'
services:
  mongo:
    container_name: mongo
    image: mongo
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
      target: test
    ports:
     - "8080:8080"
    environment:
       MONGODB_URI: mongodb://mongo:27017/test 
       NODE_ENV: production     
    depends_on: 
     - mongo 
    volumes:
     - .:/starter
     - /starter/node_modules
