version: '3.4'
services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
      target: test
    ports:
     - "8080:8080"
    environment:
       NODE_ENV: production
       MONGOMS_DEBUG: 1
    volumes:
     - .:/starter
     - /starter/node_modules
