apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-starter
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - env:
         - name: MONGO_DB_URL
           value: mongodb://nodejs-kubernetes-mongodb:27017/nodejs-kubernetes   
      - image: ybenmansour/hackathon-starter:latest
        imagePullPolicy: Always
        name: hackathon-starter
        ports:
        - containerPort: 8080
          protocol: TCP
