apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - env:
         - name: MONGODB_URI
           value: mongodb://nodejs-kubernetes-mongodb:27017/nodejs-kubernetes   
      - image: https://673294157311.dkr.ecr.eu-west-3.amazonaws.com/hackathon-starter
        imagePullPolicy: Always
        name: web
        ports:
        - containerPort: 8080
          protocol: TCP
---         
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8080        
