apiVersion: v1
kind: Service
metadata:
  labels:
    name: nodejs-kubernetes-mongodb
  name: nodejs-kubernetes-mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: nodejs-kubernetes-mongodb
