# This is a basic workflow to help you get started with Actions

name: Create Jenkins Instance

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_ec2_jenkins:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./terraform

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.4
          terraform_wrapper: false
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-3
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Initialize Terraform
        run: terraform init
        
      # Generates an execution plan for Terraform  
      - name: Plan Terraform
        continue-on-error: true
        run: terraform plan -no-color

      - name: Apply Terraform 
        id: apply
        run: terraform apply -auto-approve
      
      - name: Execute jenkins pipeline
        run: |
          echo "Ejecutando el pipeline"
          ec2_jenkins_server = $(terraform output ec2_jenkins_server)
          echo $ec2_jenkins_server
          curl $ec2_jenkins_server:8080/job/TFM%20NodeJS%20app%20pipeline/buildWithParameters --user cicdUser:TFM_CICD 
      - run: echo "Finalizando el pipeline"
      
