# This is a basic workflow to help you get started with Actions

name: Create Jenkins Instance

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create_ec2_jenkins:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./terraform

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        

      
      - name: Execute jenkins pipeline
        run: |
          ec2_jenkins_server=$(terraform output --raw ec2_jenkins_server)
          echo "Ejecutando el pipeline: " $ec2_jenkins_server
          echo http:// ${{ format('{0}:{1}', secrets.JENKINS_USER, secrets.JENKINS_PASS) }} @$ec2_jenkins_server :8080/job/TFM%20NodeJS%20app%20pipeline/build?token=TFM_CICD
          curl -I http://${{ format('{0}:{1}', secrets.JENKINS_USER, secrets.JENKINS_PASS) }}@13.38.104.19:8080/job/TFM%20NodeJS%20app%20pipeline/build?token=TFM_CICD
      
      - run: echo "Finalizando el pipeline"
      
